### ISSUE TITLE
Power Operations Support

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#10]
OpenStack Shell should provide Power Operations for the resources required. Basic wokflow looks like this - 
1. User creates an environment
2. User adds an App that uses OpenStack Cloud Provider 
3. User Reserves an environment. 
4. The App should be auto powered on. 

After this point, it should be possible to Power On/Power Off the resource. This should result in the OpenStack VM that is deployed for this resource will be Powered either On or Off. 
When the resource is Powered On, the Live status should be shown as Green.
When the resource is Powered Off, the Live status should be shown as Grey.

For an already Powered On Resource, Powering On should not result in any change and should not throw an error.
For an already Powered Off Resource, Powering Off should not result in any change and should not throw an error.

It is possible to "delete Openstack VM" for a resource (without Cloudshell knowing about it). Running Power operations on those resources should display the resource in Error or Offline condition. ie. Live status should be Offline or Error  (clear visible indication to the user that there is something wrong with the Resource) 
It should be possible to "delete such resources that are in error condition when the reservation ends (through End Reservation)

Following Commands should be supported - 
- [ ] Instance Power On
- [ ] Instance Power Off

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156316]

**Comment by Shnitselon** [comment]
documented generically for all Apps in the "Run App commands" section of: http://help.qualisystems.com/Online%20Help/7.1.0.5333/Portal/Content/CSP/LAB-MNG/RSRV-Use-Apps.htm?Highlight=apps%20in%20reservations

Added a Refresh IP command to the 8.0 help
