### ISSUE TITLE
network segmentation rename

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#103]
When we create Vlan segmentation in OpenStack, we would like their names to match this pattern:
Qs_segmentation_<VLAN ID>

We need the ability to "see" what was created by CloudShell and what no (similar to vCenter)

**Comment by gabhijit-izel** [comment]
I have renamed the networks to start as qs_net_segmentation_id - Guess that's fine

**Comment by TomerAdmon** [comment]
cool :-)

**Comment by yairbb** [comment]
@gabhijit-izel @TomerAdmon 
you see it only in Openstack portal. did you meant to see it in Cloudshell too ? like the IP presented on App ?

**Comment by TomerAdmon** [comment]
it can be seen only on Horizon... this is the name of the network in OpenStack. not reflected in CloudShell

**Comment by yairbb** [comment]
ok. bug is fixed!
