### ISSUE TITLE
Recommendations for project security group

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#104]
please provide Recommendations for project security group for documentation

**Comment by gabhijit-izel** [comment]
Recommendations are as follows - 

1. We should have the following ports open 

-ICMP Open  - (Almost always must have unless a policy prevents ICMP)
- TCP Port 22 for SSH (Ideally should be there) 
- TCP port 80/443 if running a web-server (Only if running web services that require external access).
- TCP Port 3389 for RDP On Windows (ideally should be there)

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159697&_a=tests)

**Comment by alexazarh** [comment]
The ports also must be restricted with a Remote configuration that limits the connection to the quali mgmt network CIDR or by the security group that is attached to the QX and ES. 
Examples:
1) CIDR
http://prntscr.com/ebyw8c
2) Security Group
http://prntscr.com/ebywz2
