### ISSUE TITLE
Delete Instance Support

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#11]
In OpenStack Shell - an instance is deployed through deploy instance (Deploy instance can happen directly through App -> Deploy App or through Reservation Setup).  It should be possible to Delete these instances 

The delete Instance should be supported for following scenarios
Support for deleting an OpenStack Instance created through Cloud Shell
- [ ] Delete an existing instance 
- [ ] Delete an instance already deleted
- [ ] Delete instance through reservation teardown
- [ ] Delete instance from the resource manager.

Upon deleting the VM from resource manager, VM should be deleted from Cloud Provider, ie. OpenStack.

TODO: Add error messages related information. For instance how is this dealt with when an Instance is deleted from OpenStack and you try to delete the instance from Portal UI or Resource Manager.

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156316)

**Comment by gabhijit-izel** [comment]
I think the last two lines of this story needs to be revisited. We are not freeing any resources in the delete VM (and it should be done in removeVLAN) Thanks @yairbb

**Comment by yairbb** [comment]
@alexazarh 
Alex, 
what is the conclusion regarding that ?

**Comment by alexazarh** [comment]
What Abhijit said

**Comment by gabhijit-izel** [comment]
@yairbb sorry for keeping it in-tact - updated.

**Comment by yairbb** [comment]
blocked currently by bug #122
