### ISSUE TITLE
No default route for App Connectivity Subnets

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#110]
Right now when we create Networks and Subnets for App connectivity, default routes get added to the subnets when the interfaces come up. This results in completely messed up routing tables on VM and the connectivity to VM is potentially lost. The way to fix this is - when we create a Subnet (during connectivity) we need to explicitly specify that the particular subnet does not have a default g/w

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159659&_a=tests)
