### ISSUE TITLE
Deployment option description should be removed

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#115]
Please remove the description from the deployment option.
""OpenStack Instance from Image Deployment Driver""
![image](https://cloud.githubusercontent.com/assets/12639815/21887582/29596178-d8c9-11e6-8bb6-4b10b1db8595.png)

**Comment by gabhijit-izel** [comment]
@alexazarh  Can you fix it with 24 & 101?

**Comment by alexazarh** [comment]
sure

**Comment by yairbb** [comment]
fixed!
