### ISSUE TITLE
Delete floating IP when instance is deleted

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#116]
If an Instance has associated floating IP associated with it, when the instance is deleted, delete the floating IP associated with that instance or the pool of floating IPs becomes full and subsequent association fails during reservation.

**Comment by yairbb** [comment]
@gabhijit-izel 
not clear what did you meant.

do you want to insure that the floating ip was deleted with the instance ? if yes why pool of floating ip shell be full ? The specific floating ip shell be free for the next association, no ?

**Comment by gabhijit-izel** [comment]
The way to test this is as follows - 
1. Create an App with Floating IP attribute set to True
2. Deploy App - Make sure floating IP works and you can ping to floating IP
3. Note the floating IP for the App
4. Delete the app or close the reservation 
5. Go to Horizon -> Access/Security (on left pane) -> Floating IPs 

The floating IP noted in step 3 should not be present here.

**Comment by yairbb** [comment]
Verified: 159662

[Test case](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=156316&_a=tests)
