### ISSUE TITLE
Cancellation support for OpenStack "deploy from glance" deployment option

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#118]
We would like the OpenStack "deploy from glance" deployment option to have cancellation support so users will be able to cancel the deployment if needed and the system will be able end the sandbox setup in case needed.

@gabhijit-izel  - please reefer to AWS or azure deployment options for example implementation.

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159302&_a=tests)
