### ISSUE TITLE
Configure 2nd compute node

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#120]
IP: 192.168.170.4
Credentials are in the email.

**Comment by gabhijit-izel** [comment]
Configuration is done and I have deployed one VM on this node and I am able to login to it's console. One small thing is remaining. The Ethernet interface eth1 is probably not connected. Gal or someone just has to plugin that wire then we can test some Vxlan testing as well.

**Comment by alexazarh** [comment]
Need to document the installation process

**Comment by gabhijit-izel** [comment]
Changed the `/etc/apt/source.list.d/` as follows and used packages from cloud-archive-liberty

```
root@Node3:/etc/apt/sources.list.d# cat cloud-archive-liberty.list 
deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main
# deb-src http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main
```
After that 

```
sudo apt-get update
sudo apt-get install nova-compute

```

**Comment by gabhijit-izel** [comment]
Verified after deploying an instance ping to g/w works - so VxLan works as well.
```
19:55:30.994045 IP 192.168.93.5.40016 > 192.168.93.3.8472: OTV, flags [I] (0x08), overlay 0, instance 91
IP 172.16.1.20 > 172.16.1.1: ICMP echo request, id 32257, seq 0, length 64
19:55:30.994482 IP 192.168.93.3.45590 > 192.168.93.5.8472: OTV, flags [I] (0x08), overlay 0, instance 91
IP 172.16.1.1 > 172.16.1.20: ICMP echo reply, id 32257, seq 0, length 64
```

Deployment works closing this.

**Comment by Shnitselon** [comment]
Hi Abhijit, do you have the installation instructions?
#gabhijit-izel

**Comment by gabhijit-izel** [comment]
For the compute node? I believe - we don't need to have installation instructions for compute and/or controller nodes because we assume they are already deployed. However - I will update the link that I followed here. (But even then we should not be covering this particular thing in documentation) @TomerAdmon @alexazarh is that correct?

**Comment by Shnitselon** [comment]
@TomerAdmon @alexazarh  anything to document?

**Comment by TomerAdmon** [comment]
@Shnitselon  - nope :-)
