### ISSUE TITLE
Installation Description is missing

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#121]
In the App attribute "Installation" field is missing description.

**Comment by yairbb** [comment]
@TomerAdmon 
what do you think ? is that redundant to add it ? even there is drop down it will be more clear to the user .

**Comment by TomerAdmon** [comment]
@yairbb - please add more details, print screen.... what is the 'App attribute "Installation" field'?

**Comment by yairbb** [comment]
![image](https://cloud.githubusercontent.com/assets/20166257/21984270/d6eb0d64-dbfd-11e6-80fd-706fa71e3f50.png)

**Comment by yairbb** [comment]
@TomerAdmon 
not sure shell be updated ... but will be better.

**Comment by TomerAdmon** [comment]
This is related to the app deployment process and not to the Shell. 
please close.

**Comment by yairbb** [comment]
@TomerAdmon 

and due to that there is no need to supply description ?

**Comment by TomerAdmon** [comment]
This is not an attribute.
This field controls the installation process of the app.
after we deploy the VM, we are planning to install an application on it, this field will contain available installation scripts that can be applied to install the application on the VM.
Anyway, if you think a description is missing, please contact Ariel.

**Comment by yairbb** [comment]
Ok. I only want the user to understand each field he has .
