### ISSUE TITLE
Delete Resource from API Command.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#122]
STR:

1) Have a reservation with 1 App deployed.
2) Use XMLRPC DeleteResource API command to delete the Resource.

BID:
The Resource shell be deleted from Cloudshell and from Open Stack as well.

Actually : The Resource is deleting from Cloudshell and not from RM. After some Refresh operation  it becomes valid in RM and presented again in Cloudshell. In openstack portal it was deleted.

**Comment by gabhijit-izel** [comment]
Hi,

I am not entirely sure how to go about fixing it. Can you please tell me how to test for this particular bug?

**Comment by TomerAdmon** [comment]
@alexazarh  - please assist

**Comment by alexazarh** [comment]
@yairbb 
1. What error do you get?
2. Please attach server logs and shell logs
3. If you delete the deployed app resource from the resource manager, does it work or fails with the same error?

**Comment by yairbb** [comment]
Attached the logs:

[Logs](\\qsnas1\Shared\Yair_Ben_Chaim\Logs)

there is no error in case you delete it from the RM.

**Comment by alexazarh** [comment]
I asked @shaykeren to look at the server logs

**Comment by yairbb** [comment]
Ok. Good!
