### ISSUE TITLE
Connectivity: Error message not clear.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#126]
STR:
1) Have a reservation with deployed App connected to vlan.
2) Add un deployed App to reservation.
3) Connect the App to the Deployed App.

BID: An error shall be obtained : "Please deploy First!!!"

Actually an Error obtained but not so specific  : " All connections failed: Failed to attach Subnet to Network "

**Comment by yairbb** [comment]
logs:

\\qsnas1\Shared\Yair_Ben_Chaim\Logs

**Comment by TomerAdmon** [comment]
@yairbb - can you please add print screen?

**Comment by yairbb** [comment]
fixed but related to bug #127
