### ISSUE TITLE
Connectivity:  list index out of range error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#127]
STR:
1) Have an Env with undeplotyed App connected to Auto Vlan.
2) Reserve the env. 
BID:
1) no error shell be obtained

Actually:

An Error:" list index out of range " was obtained.

**Comment by yairbb** [comment]
Logs:

\\qsnas1\Shared\Yair_Ben_Chaim\Logs3

**Comment by yairbb** [comment]
![image](https://cloud.githubusercontent.com/assets/20166257/22196952/70093fa2-e158-11e6-8773-792ddd06a8aa.png)

**Comment by gabhijit-izel** [comment]
@yairbb Can you please copy paste logs here?  I don't have access to qsnas1

**Comment by yairbb** [comment]
fixed!

**Comment by gabhijit-izel** [comment]
Re-opened this is probably similar to #86. Since we have closed that, let this remain open.

**Comment by yairbb** [comment]
fixed!

**Comment by yairbb** [comment]
fixed!
