### ISSUE TITLE
Connectivity: Partially connected

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#128]
STR:
Have a reservation with deployed App connected to vlan.
Add un deployed App to reservation.
Connect the App to the Deployed App.
BID: An error shall be obtained : "Please deploy First!!!"

Actually:Partially Conected apear.

I will sent to yuo logs by mail.

**Comment by TomerAdmon** [comment]
It sounds like the correct behavior, like in vCenter...
let's talk.

**Comment by alexazarh** [comment]
@yairbb please talk to me about this bug

**Comment by yairbb** [comment]
not a bug.
