### ISSUE TITLE
Connectiom Error: 2 types vlan error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#139]
STR:
1) Reserve a P2P blueprint in the IL OpenStack
2) Remove one of the apps (it will be removed from the sandbox)
3)	Add another undeployed app
4)	Create a connector request between the undeployed app and the deployed app
5)	Execute “connect” on the connector request

BID:

Partially connected shell be obtained from the connection command.

Actually an error is obtained: "Could not resolve VLAN for of two different VLAN types” "

**Comment by GilGald** [comment]
Note that the id of the failing vlan is :4096

**Comment by gabhijit-izel** [comment]
Yes - very similarly for #137. So I guess one should first use correct VLAN ID?

**Comment by yairbb** [comment]
@gabhijit-izel 

No connection to #137. 

gil will fix this bug in the server.

**Comment by yairbb** [comment]
fixed!
