### ISSUE TITLE
QualiX Integration with OpenStack

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#14]
When OpenStack Linux instances are created from Cloudshell, we should be able to SSH to those instances through QualiX
- [ ] Deploy QualiX server in Lab
- [ ] Understand QualiX server setup requirements
- [ ] Design changes required at QualiX side to integrate with OpenStack
- [ ] Integrate QualiX server with VM Deployment

**Comment by gabhijit-izel** [comment]
On the CentOS image that we have, I have deployed quali server and taken a snapshot of that particular CentOS image. This should be a good starting point for all QualiX configuration.

**Comment by gabhijit-izel** [comment]
Basic deployment of QualiX works now - after a new rule to connect to QualiX VM is added in "Default" security group. For now modified "default" security group to allow port 80 and port 443. We can either create a separate one (and document it) or just update the default. @TomerAdmon @alexazarh your suggestions?

**Comment by TomerAdmon** [comment]
I think we should document it to be in another security group...

**Comment by alexazarh** [comment]
I agree with @TomerAdmon

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/1%20-%20Shells/_testManagement?planId=125053&suiteId=159743&_a=tests)

**Comment by yairbb** [comment]
was tested in BDT . Santiy test was performed.

**Comment by yairbb** [comment]
@TomerAdmon 

shell we document this ?
