### ISSUE TITLE
Floating IP error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#141]
STR:

1) Have a Reservation with some deployed App (more than 10 ) all with floating IP connected to vlan ( not sure it is important)
2) Teardown.

BIR:

All the VM's and their connections  shall be removed from OpenStack.

Actually the reservation is in "Completed" state but all the VM's are still powered on in cloudshell and in Openstack portal.

**Comment by yairbb** [comment]
[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/742231/TeamServer.Service.txt)

**Comment by gabhijit-izel** [comment]
More logs? Not facing the error with latest develop code.

**Comment by yairbb** [comment]
Currently the bug is not reproduced. I assume that some how it was fixed. 
closing it !
