### ISSUE TITLE
Tenant Networks are created in shared mode

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#142]

**Comment by alexazarh** [comment]
This is an open stack limitation and nothing we can do about it

**Comment by gabhijit-izel** [comment]
This is a consequence of how networking works in OpenStack. We need to document following - 

1. For the VLAN services, Administrator should define non overlapping ranges for every "Cloud Provider". This is a consequence of the fact that - provider networks that we are creating are shared across the tenants. 

For example: There are two projects Project A and Project B. It is possible that a Provider Network created by Project A can be used by Project B. The solution to that is to use Tenant networks (with lesser permissions) however OpenStack does not allow to explicitly use "Segmentation ID" which might be required by VLAN Services - where this typically comes from Quali Server and Shell cannot choose.

**Comment by gabhijit-izel** [comment]
@TomerAdmon @alexazarh @Shnitselon please take a look at comment above.

**Comment by alexazarh** [comment]
The allocation of the vlan services is done based of the pool id. By default the pool that is used is the CloudShell domain. So the admin should define the non overlapping ranges in the vlan services per the pool id (not per cloud provider)

**Comment by Shnitselon** [comment]
Is this specific to OpenStack?

@alexazarh @gabhijit-izel

**Comment by alexazarh** [comment]
Yes

Best regards,
Alex Azarh

**Comment by Shnitselon** [comment]
How's this note (in the OpenStack Configuration Requirements topic):

Provider networks: OpenStack provider networks are shared for all projects in your OpenStack installation. Therefore, to avoid ID collisions, make sure the VLAN services that will be used for OpenStack VM connectivity do not have overlapping ranges for the same pool id.

@alexazarh @gabhijit-izel

**Comment by alexazarh** [comment]
I think its ok
