### ISSUE TITLE
Powered Off error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#144]
STR:
1) Have a reservation with deployed App.
2) Power off command

BID:

The VM shell be power off with no error.

actually:

an error is obtained due to that .

**Comment by TomerAdmon** [comment]
@yairbb  - can you add print screen and logs?

**Comment by yairbb** [comment]
sure !
![image](https://cloud.githubusercontent.com/assets/20166257/22545360/2242b226-e941-11e6-843b-88e1c6e0a1cb.png)


logs are in:

\\qsnas1\Shared\Yair_Ben_Chaim\Logs4

**Comment by yairbb** [comment]
fixed!
