### ISSUE TITLE
Deployment Type Icon

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#148]
The same Icons were configured to deployment type and Cloud provider.

Deployment type icon shall be fixed.

**Comment by yairbb** [comment]
@gabhijit-izel 
Cloud Provider:
![openstack vm_icon 2x](https://cloud.githubusercontent.com/assets/20166257/22639788/72ac8ac4-ec58-11e6-8248-0cbb4f2d03f4.png)

Deployment type:
![openstack vm 2x](https://cloud.githubusercontent.com/assets/20166257/22639815/87e960f6-ec58-11e6-93b8-ad2b78dd3358.png)

**Comment by gabhijit-izel** [comment]
Hi Are you sure this is the problem? I am seeing two different Icons - (attaching screen shots)

**Comment by gabhijit-izel** [comment]
![cloud_provider_icon_screen](https://cloud.githubusercontent.com/assets/17586985/22655467/3c93dd30-ecb6-11e6-8db6-a176d3fed624.png)
![openstack_app_icon](https://cloud.githubusercontent.com/assets/17586985/22655475/434e3102-ecb6-11e6-810e-3190a719cb76.png)

**Comment by gabhijit-izel** [comment]
Sorry accidentally closed.

**Comment by gabhijit-izel** [comment]
The files I am using look inverted. Is that correct?

**Comment by TomerAdmon** [comment]
@gabhijit-izel - let's switch the icons in the Shell to match what described in Confluence & in the attributes PDF.

**Comment by yairbb** [comment]
looks ok.
