### ISSUE TITLE
Connectivity without Vlan

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#150]
STR:
1) Have an env with 2 Un deployed Apps connected CVC(Requested)
2) Setup

BIR:
The setup shall be succeeded with 2 deployed Apps connected.
Actually: Its failed with Error:"cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: Failed to Create Network with VLAN ID 5:Raised Exception (type 'exceptions.IndexError') list index out of range. Failed to Create Network with VLAN ID 5:Raised Exception (type 'exceptions.IndexError') list index out of range
"

**Comment by yairbb** [comment]
[DisPro.txt](https://github.com/QualiSystems/OpenStack-Shell/files/754861/DisPro.txt)


[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/754863/TeamServer.Service.txt)

**Comment by gabhijit-izel** [comment]
Let's debug this together sometime. Let me know when.

**Comment by yairbb** [comment]
fixed!
