### ISSUE TITLE
Failed to execute reload for OpenStack resource

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#156]
STR:
1) have an OpenStack resoruce
2) open the inventory page
3) click "discover" on the resource
4) on the discovery page, click start discovery

result:
![image](https://cloud.githubusercontent.com/assets/12639815/22862506/bbf10630-f138-11e6-9318-6265825293ae.png)

**Comment by alexazarh** [comment]
@TomerAdmon / @yairbb 
Its a knows problem. When you open the discover popup again the attributes of type password are not populated with the correct value. They are populated with a placeholder that is used by the server to know if the value was changed or not. But when you run the discover the correct password value is overridden with the placeholder. The bug should be open in TFS.

**Comment by TomerAdmon** [comment]
@fixed by @shaykeren
