### ISSUE TITLE
Availability zone support

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#157]
As an admin, i would like to be able to choose an 'Availability zone' on an app to choose where the deployed machine will be deployed.
this won't be configured on the cloud provider so it shouldn't be validated as part of the auto-load.

If the availability zone name doesn't exist, deploy VM should throw a an error mentioning that the deplo failed since the availability zone exist.

Empty availability zone is valid and allow the OpenStack to choose any of the available ones

http://docs.openstack.org/mitaka/networking-guide/config-az.html

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement]

**Comment by TomerAdmon** [comment]
@yairbb  - bad link, please fix

**Comment by yairbb** [comment]
why ? it works . try again
