### ISSUE TITLE
Security Groups Support

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#16]
Whenever an Instance is deployed, it should be possible to connect to the instance on specified ports through Deploy Resource Inbound and Outbound ports. The security groups required by QualiX and CloudShell execution server will automatically be added. This use case is about defining custom security groups (inbound or outbound ports) specific to the application that are going to enable an external user to remotely connect to the App. Another use case would be in a scenario with an application components not in the sandbox, such as a shared directory service or a plugin.
- [ ] Support Defining Security Groups in OpenStack 
- [ ] Support assigning Security Groups to Instance

**Comment by yairbb** [comment]
Current not final:

(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156512]

**Comment by gabhijit-izel** [comment]
One idea right now is to support 'a default security group' when we use floating IP
