### ISSUE TITLE
Image flavor: bad Error message when image flavor is missing

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#160]
Try to deploy a VM without a flavor size. 
The error you wll get is:
![image](https://cloud.githubusercontent.com/assets/12639815/22877741/7a490d20-f1df-11e6-8733-3f57853f0a5b.png)

It should say:
"No Flavor was set on the app, please set a Flavor and try again"

**Comment by yairbb** [comment]
@TomerAdmon @alexazarh 
Fixed!

but the error is little bit different from what you suggest:"Instance flavor cannot be empty."

closed this issue.
