### ISSUE TITLE
Floating IP subnet UUID attribute

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#165]
The attribute appears twice in the CP Resource and in the App attribute too.

Duplicate shell be fixed.

**Comment by TomerAdmon** [comment]
@yairbb  - hi, please take a look at #195 & in the confluence. the attribute 'Floating IP Subnet Id' should be both on the CP and in the App.

let me know if i got it wrong

**Comment by yairbb** [comment]
@TomerAdmon 
Yes. But in the Deployment option it shell not be user input.

**Comment by alexazarh** [comment]
@yairbb why its a P1 bug?

**Comment by TomerAdmon** [comment]
Updated to P3, this attribute should be on the app not as a user input as described in the Conflucne page
![image](https://cloud.githubusercontent.com/assets/12639815/22923511/78c46a3c-f2aa-11e6-8294-c2e00ee4a29b.png)

**Comment by yairbb** [comment]
@alexazarh 
I think that the customer will ask why it's duplicate . this is the reason why I set it to p1.

**Comment by alexazarh** [comment]
@yairbb 
Please not that P1 bugs should be only for critical bugs that are blocking a story.

**Comment by yairbb** [comment]
Reopen . it still duplicate. no need

**Comment by yairbb** [comment]
Ok. got it . I misunderstand the point here.

closing
