### ISSUE TITLE
Error during app deployment doesn't reflects in CloudShell

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#166]
### Steps to reproduce

1) Have a blueprint with app that uses m1.large flavor
2) reserve the blueprint

### actual result:
The CloudShell App keep spinning for at least 10 min.
The instance failed to start on OpenStack:
![image](https://cloud.githubusercontent.com/assets/12639815/22890668/bab43f7a-f215-11e6-8e92-72923bc43785.png)

### expected result:
The error should be reflected in CloudShell and the sandbox should be failed

**Comment by yairbb** [comment]
@TomerAdmon 
was it only with the win image ?

**Comment by TomerAdmon** [comment]
@yairbb - not only Windows.

**Comment by yairbb** [comment]
tested and found OK.

I assume that the lack of CPU was the problem.
Closing this bug. will be reopen if will reproduced if will be again in the future.
