### ISSUE TITLE
BDTOpenStack: openstack:when creating an app from openstack cloud provider- parameter named availability zone- deoesn't have suuficient description

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/OpenStack-Shell#167]
openstack:when creating an app from openstack cloud provider- parameter named availability zone- deoesn't have suuficient description

STR:
1.log into the portal in domainA
2.create an app from cloud provider open stack

BIR:
if the parameter availability zone -doesn't have useful description:

**Comment by GilGald** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15359652/22922776/bdf5fb6e-f2a7-11e6-9195-07b80269fabe.jpg)

**Comment by TomerAdmon** [comment]
@GilGald  - Thanks Gil, The proper description that should be there as described in Confluence:
"""Name of availability zone the VM will be associated with. Availability zone used to group network nodes for making network resources highly available."""
http://confluence.quali.com/pages/viewpage.action?pageId=33652772
