### ISSUE TITLE
BDTOpenStack: Image UUID should be changed to Image ID

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/OpenStack-Shell#168]
When creating a new APP check the description.

**Comment by GilGald** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/15359652/22923242/4c3ea55a-f2a9-11e6-9b0a-ed72473e190b.jpg)

**Comment by TomerAdmon** [comment]
Thanks @GilGald, this will be fixed as part of #49  - It's already described in Confluence
