### ISSUE TITLE
BDTOpenStack: Not mandatory inputs are not mentioned as not mandatory.

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/OpenStack-Shell#169]
Create a new app .
User might think the inputs in the picture are mandatory.

**Comment by GilGald** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15359652/22923446/2a72ca36-f2aa-11e6-87a2-9445e6140228.jpg)

**Comment by TomerAdmon** [comment]
Thanks @GilGald  - updated the Confluence page, this will be fiexed as part of #49

**Comment by yairbb** [comment]
fixed!
