### ISSUE TITLE
BDTOpenStack:The Url field in the Configuration tab when the tool is set to scripts says "playbook" in the description

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/OpenStack-Shell#170]
Playbook is for ansible not for script

**Comment by GilGald** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/15359652/22924362/78b562c8-f2ad-11e6-9387-7f6d9784f925.jpg)

**Comment by TomerAdmon** [comment]
@GilGald / @yairbb   - please close and open it in TFS, this is not related to OpenStack.

**Comment by GilGald** [comment]
@yairbb  can you do that please?

**Comment by yairbb** [comment]
Passed to Shay Scrum!

**Comment by yairbb** [comment]
Done!
