### ISSUE TITLE
Defining a username and password for an app template does not overwrite the machine's default username and password

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/OpenStack-Shell#171]
1. Log onto http://192.168.170.201 as admin
2. Change one of the Cirros Apps ("OpenStalkers" for example) so that it has a username and password.
3. Reserve a blueprint with the app. 
4. Try to connect via SSH. 

BIR if connection fails. 

Manually change the deployed app's username and attributes via the sandbox to user "cirros" and password "cubswin:)" and connect. Connection is successful as these are the machine instance's default username and password.

**Comment by TomerAdmon** [comment]
@TaiTheGreat  -  this is not the behavior in OpenStack. In OpenStack as in vCenter, the Image should be preconfigured with user name or password and they should be preconfigured on the app.
let me know if i misunderstood the scenario.
