### ISSUE TITLE
Password not Empty

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#178]
STR: 

Discover OpenStack CP with no input to the "Openstack user Password". looks like there is a default Value "......". 

BIR:
Get error.

In case to prevent it the field shell be empty without the "....."

See the attached PrntScrn

**Comment by yairbb** [comment]
![capture](https://cloud.githubusercontent.com/assets/20166257/22977891/2ce4c126-f399-11e6-8d56-ced9153bc065.PNG)

**Comment by alexazarh** [comment]
@yairbb This is the default behavior of password attributes. Nothing to do on the openstack shell side. You may open a buug in the tfs if you think there is a functional bug.

**Comment by yairbb** [comment]
it's not a functional bug its visibility bug. I will transfer it to tfs.
