### ISSUE TITLE
Error in error message.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#179]
Error in the description:"OpenStack Passwrd Cannot be empty"

shall be fixed to Password.

**Comment by yairbb** [comment]
![capture](https://cloud.githubusercontent.com/assets/20166257/22978091/ed7f67e2-f399-11e6-8678-5f7efbd62d39.PNG)

**Comment by TomerAdmon** [comment]
Passwrd ==> Password

**Comment by yairbb** [comment]
fixed!
