### ISSUE TITLE
Setting Resource state to Error does not delete Resource

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#18]
When we try to power on/ power off an instance through UI Commands for an instance which has otherwise been deleted by OpenStack (through some Out of band mechanism). If we SetAttributeStatus to "Error", the resource is not deleted when the reservation is tear down.

**Comment by gabhijit-izel** [comment]
While testing with fix for #38 this is not observed. So should I directly move it to closed?

**Comment by alexazarh** [comment]
@gabhijit-izel  Only PV can move issues to the Done column. If you resolve a bug please move it to the Resolved column

**Comment by yairbb** [comment]
Fixed!
