### ISSUE TITLE
Deploy Command Error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#184]
STR:

1) Have an Env with 2 deployed centos Apps connected to vlan. ( dont think it is important)
2) add to the reservation new centos App.
3) deploy command.

BIR:

Error is obtained:

Deploy App ended with status Failed with error: Failed to start execution: Failed to set up the python environment for the driver, error installing driver dependencies.

BTW: Using the setup command it is ok.

**Comment by yairbb** [comment]
![capture](https://cloud.githubusercontent.com/assets/20166257/23025700/7c1dec26-f467-11e6-9e44-bdd449a134df.PNG)

**Comment by yairbb** [comment]
logs:

[DisPro.txt](https://github.com/QualiSystems/OpenStack-Shell/files/780441/DisPro.txt)




[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/780442/TeamServer.Service.txt)

**Comment by alexazarh** [comment]
@yairbb Where are the Execution Server logs?

**Comment by yairbb** [comment]
Currently run smoothly.

close it  !
