### ISSUE TITLE
Add floating IP Default Value.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#185]
According to the http://confluence.quali.com/pages/viewpage.action?pageId=33652772

there is no default Value.

Actually: False is the default Value in the attribute.

**Comment by TomerAdmon** [comment]
@yairbb - Since Boolean value must have a default value, we will go with False as the default. can you update the Confluence page?

**Comment by yairbb** [comment]
fixed in conf.
