### ISSUE TITLE
Floating IP Subnet Id description

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#186]
Missing "Optional" in the begining of the description according to the conf.

**Comment by alexazarh** [comment]
@TomerAdmon  please update the confluence page with the correct description. At the moment the description is the same as it was before...

**Comment by yairbb** [comment]
@alexazarh 
reopen not fixed!

**Comment by alexazarh** [comment]
We talked about it and it should be the way it is

**Comment by yairbb** [comment]
since this attribute is in CP we will not add "Optional"  to the Description.
