### ISSUE TITLE
*Testing Only* - Reserved networks

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#188]
As an admin i would like to create a black-list for netowkrs (CIDRs) that i wouldn't like to use for subnet allocation in the apply-connectivity phase. 
Common Example is a managment network, that every machine should be connected to in subnet 192.168.120.0/24, in this case we wouldn't like CloudShell to override this connection rather "skip" this connection and generate a connection on another subnet, for example 192.186.121.0/24.
Testing should include positive cases, negative cases and edge cases when there are several reserved networks, for example: 192.168.0.0/24, 10.0.0.0/24, 172.0.0.0/24

Referance we have from vCenter-Shell

http://team:8080/tfs/Quali-Collection/QualiSystems/1%20-%20Shells/_testManagement?planId=125053&suiteId=158951&_a=tests

**Comment by TomerAdmon** [comment]
Please see #75 that is currently limits the feature functionality. 
Add test cases related to #75

**Comment by TomerAdmon** [comment]
@yairbb  - R U working on it?

**Comment by yairbb** [comment]
not yet.

**Comment by yairbb** [comment]
Pass the issue to resolved if you want to prioritize it.
Even I promise to do sanity check on that ….

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/1%20-%20Shells/_testManagement?planId=125053&suiteId=158951&_a=tests)
