### ISSUE TITLE
update 'OpenStack Physical Interface Name' attriute description

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#189]
update 'OpenStack Physical Interface Name' attriute description mentioning that it's not required when using VXLAN

**Comment by yairbb** [comment]
@alexazarh 

fixed!

Q: in the description you refer in the example only to linux bridge. Is that relevant to vswitch too ?

look at that:
" The physical interface mapping name to use when configuring OpenStack connectivity. The physical interface can be found under the connectivity provider configuration. If VXLAN is set as the 'VLAN Type' this attribute is not required. For example, for OpenStack deployments that use the Linux-Bridge plugin, the physical interface name is located in the linuxbridge_agent.ini file under the “physical_interface_mappings” attribute"
