### ISSUE TITLE
no option to ping with Centos to Centos with vlan IP

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#190]
STR:

1) Have an env  with 2 Centos  Un Deployed App set Auto Udev to True Availability zone Bla.
2) Add vlan and connect to all the VMs .
3) Setup

BID:
no Option to ping from Centos to the second Centos VM using the vlan IP.

The BID is with Setup and deploy command. In both of the  cases.

**Comment by yairbb** [comment]
Logs:
[DisPro.txt](https://github.com/QualiSystems/OpenStack-Shell/files/789595/DisPro.txt)


[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/789596/TeamServer.Service.txt)

**Comment by yairbb** [comment]
Logs attached again:






[Logs 1.zip](https://github.com/QualiSystems/OpenStack-Shell/files/790113/Logs.1.zip)

**Comment by yairbb** [comment]
@alexazarh @gabhijit-izel 
currently it working with bla but not good with ovs.
Alex mentioned that it coud be due to dhcp configuration.
pls take it into account.

**Comment by alexazarh** [comment]
blocked by #193

**Comment by yairbb** [comment]
@gabhijit-izel @alexazarh @TomerAdmon 

it seems work fine only after soft reset.

**Comment by yairbb** [comment]
@gabhijit-izel 

The reset shell be part of the script that configures the Udev.

**Comment by yairbb** [comment]
fixed!
