### ISSUE TITLE
instance is not getting deleted when deploy failed because the flavor size is too small

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#191]
instance is not getting deleted when deploy failed because the flavor size is too small

**Comment by alexazarh** [comment]
This bug is not reproduced on Liberty. I have seen it happen on Kilo.
In Liberty an instance is never created but in Kilo an instance starts spawning, fails and is not deleted...

**Comment by alexazarh** [comment]
@gabhijit-izel have you encountered this before?

**Comment by yairbb** [comment]
closed!
