### ISSUE TITLE
Migrate entire IL deployment to OVS

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#193]

**Comment by gabhijit-izel** [comment]
Current OpenStack deployment in Israel - is as follows 

Controller Node - Linux Bridge
Compute Nodes - OpenVswitch

OpenVSwitch is not deployed on Controller node as we do not have extra unnumbered interface (required by OpenVSwitch). Tried to use existing interface - but this results in loss of all connectivity. So we are leaving the setup as it is - as the choice of L2 mechanism should not matter much.

Performed a basic Sanity with connectivity and the setup looks ok. 

Important notes: 
1. currently supported L2 drivers are in `/etc/neutron/plugins/ml2/ml2_conf.ini` (note: `openvswitch`, `linuxbridge` should be present). 

2. Few tips about debugging - Typically OVS agents on Compute Nodes should be started after all the neutron services are started on controller nodes - (if a service restart is performed on Controller node). 

3. Also - make sure that the `br-int` and `br-tun` interfaces on Compute nodes are up or better to start those interfaces up using `ip link set <br-int|br-tun> up`. Check for this - if there are connectivity errors.
