### ISSUE TITLE
Floating ips not working on a prev version

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#194]
BadRequest: Unable to associate floating IP 10.53.212.99 to fixed IP 192.168.100.109 for instance 38b33990-0b43-473a-b15b-2a1167f396e8. Error: External network 31201463-2b7d-40d1-9a2f-077d9074dccc is not reachable from subnet 001beb54-cbc9-441c-9b6e-6105c7b2f947.  Therefore, cannot associate Port 50ca6191-2519-4e34-aed8-3ad5173eeee9 with a Floating IP.

OpenStack flavor:
OpenStack Nova 
Keystone v2
Neutron* with VXLAN & OVS
Kilo with KVM

**Comment by gabhijit-izel** [comment]
@alexazarh : is it possible to share the network topology? It looks more like a problem with routing than Floating IP per se.
