### ISSUE TITLE
Ubuntu VM cant Ping

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#198]
Still not able to ping from Ubuntu to Ubuntu using the vlan IP with the new image.

**Comment by yairbb** [comment]
Logs:
[logs.zip](https://github.com/QualiSystems/OpenStack-Shell/files/795800/logs.zip)

**Comment by gabhijit-izel** [comment]
I will create a snapshot without NetworkManager and test this later today.

**Comment by yairbb** [comment]
Fixed!

Ubuntu 16.04 Server2 (ubuntu:ubuntu) is working fine !
