### ISSUE TITLE
Duplicate badges appear on Readme

### ISSUE THREAD

**Issue by borismod** [QualiSystems/OpenStack-Shell#2]
The following badges are duplicate: Waffle and Coveralls

**Comment by gabhijit-izel** [comment]
@borismod : I don't think waffle badges are duplicate. There's one badge for "Ready" and one badge for "In Progress". Coveralls badges are duplicate. Cleaning them up.

**Comment by borismod** [comment]
@gabhijit-izel agreed. Can you move this issue to InProgress when you start working on it?
