### ISSUE TITLE
windows ports are not open

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#213]
Windows VM ports 80,3389 and ~439~ 443 shall be opened.

Actually all are closed.

**Comment by TomerAdmon** [comment]
@yairbb - when do you expect these port to be open?  
What is 439? pretty sure it shouldn't be open....

**Comment by gabhijit-izel** [comment]
@yairbb : I am not getting this bug. What we have in #104 are recommended settings and not 'required' settings. So an openstack administrator is free to configure security groups the way (s)he wants. There is no 'requirement' that these ports be open. 

Also what ports are open inside an Image is a function of image and we don't mandate that (unless required for cloudshell working). 

@TomerAdmon @alexazarh : I think this bug should be closed. 

May be we should open a documentation bug - if we "require" port 3389 to be open in Windows image.

**Comment by yairbb** [comment]
take a look on #104

**Comment by alexazarh** [comment]
I agree that this bug should be closed

**Comment by TomerAdmon** [comment]
@yairbb  - it's shouldn't be OOTB... this is scenario specific...
