### ISSUE TITLE
Self-signed SSL certificates

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#214]
It is possible that in many deployments, self signed certificates are used during deployment.

If we connect to endpoints with self-signed certificates, certificate validation fails. 

We should support this - by ignoring the Server Certificate validation. 

Also - we should document that "Server Certificates are ignored, since Quali Execution Server is on premise.

**Comment by yairbb** [comment]
fixed!

From PV performed Sanity check to insure that  there is no break.
