### ISSUE TITLE
Support creating & validating new openstack controller in the inventory

### ISSUE THREAD

**Issue by menib** [QualiSystems/OpenStack-Shell#22]
The package should include a resource template that lets the admin create new openstack controller in the inventory. 
User flow: 
- Sys admin 
  - goes to inventory and clicks 'New Resource'
  - selects the 'OpenStack" resource template 
  -  Inserts the attributes that are needed to create openstack controller
- CloudShell 
  - Creates a new resource in the inventory and validates the attributes (make sure the connection to the API is valid)
  -  Runs the autoload ('get_inventory') function that loads the details of the controller to the

**Comment by TomerAdmon** [comment]
Here is the list of validation we would like to implement in the autoload:
Authentication - validate the domain, user, password and the project
Default security group - make sure that the project have a Default security group (tenant)
Management network - exist, the network should be shared
Reserved networks- valid CIDR prefix
VLAN - type-try to create a network and see that the network created successful and delete it after validation (make sure with don't leave any trash)
Provider network interface - covered in the VLAN validation
External network- exist, type should be external
Region - @gabhijit-izel please check and reply back

**Comment by gabhijit-izel** [comment]
The way to validate "Region" is as follows - There is no 'authentiation' per region. So if "Region" is empty it's okay, if it's non-empty we should use keystoneclient to validate that a region with that  particular "id" exists. Default is RegionOne (name and Id are same). That should be enough validation.

**Comment by yairbb** [comment]
Not Final
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159709&_a=tests)

**Comment by yairbb** [comment]
Region was removed.
