### ISSUE TITLE
Do not hard code test VLAN 42 on discovery validation

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/OpenStack-Shell#227]
### Issue details

When discovering the Cloud Provider, to test permissions on connectivity, VLAN 42 is created. This is a hard coded value.

https://github.com/QualiSystems/OpenStack-Shell/search?utf8=%E2%9C%93&q=42&type=

This is not good design and hurt a recent major POV. If a customer has VLAN 42 in use already, discovery fails.

### Steps to reproduce

Create an OpenStack environment that uses VLAN 42 for something. In this case, the tunnel VLAN, but could be anything. Then add Cloud Provider in CloudShell and see it fails discovery.

### Affected versions:
CloudShell 8.0 with latest release as of 6/27/17

**Comment by joerooney** [comment]
please be advised that the POV referenced represents a high profile, strategic Q3 opportunity

**Comment by alexazarh** [comment]
Fixed in release 1.0.2
