### ISSUE TITLE
Use the Resource Address for Controller URL

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#24]
Since we already have resource IP, the controller URL "IP" part should be taken from this.

**Comment by yairbb** [comment]
need to add test case to attribute TP.

**Comment by TomerAdmon** [comment]
Please remove the resource address from the resource template, something like this:
![image](https://cloud.githubusercontent.com/assets/12639815/21673437/90a48d8c-d331-11e6-9203-417c7b8ad5c3.png)

**Comment by yairbb** [comment]
Currently we have only the URL.
