### ISSUE TITLE
Add Quali management network ID as mandatory attribute

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#25]
For assigning internal IP address to deployed VMs, it is required to attach a NIC on an interface that is attached to QualiX Network. Usually this network is already created by "admin" (of type provider VLAN). OpenStack APIs allow searching for a network by the name of the network. This name should come as a cloud provider resource attribute.

**Comment by gabhijit-izel** [comment]
Actually - rather than using Quali Network "Name", Network UUID should be used.

**Comment by yairbb** [comment]
Fixed!
