### ISSUE TITLE
OpenStack not working with version 7.2

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#31]
currently version 7.2 not supported OpenStack shell. Meanwhile OpenStack shall run on 7.1GA

**Comment by AdamSharon** [comment]
fixed - now shell can work with Cloud Provider attribute (as in 7.1) and with the property (as in 7.2)

**Comment by alexazarh** [comment]
related to #48

**Comment by yairbb** [comment]
work with 7.2!
