### ISSUE TITLE
Deploy 2 Apps in the same reservation.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#32]
There should be option to deploy more than 1 App in the same reservation.
Currently , Deployment get Failed in case of 2 Apps deployment in the same reservation.

**Comment by gabhijit-izel** [comment]
Can you tell me how did you test it? Because if I add more than 1 app in environment and then reserve that environment, it works fine.

**Comment by yairbb** [comment]
Very simple add 2 apps and reserve it . it fail active with error.

I did it again with only 1 app and it works fine .

**Comment by gabhijit-izel** [comment]
So here is what I tried - I created an empty Reservation. Added two Apps and manually Ran Deploy App for both the Apps. That works fine. I also created an "Environment" added 6 Apps to it and reserved that environment. I am successfully able to deploy all 6 apps. So let's discuss what exactly is not working at your end.

**Comment by yairbb** [comment]
there  was a problem with the attribute input cloud provider.
