### ISSUE TITLE
Private IP instead of Public IP

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#34]
In the attribute panel, the public IP shall be appear  after deployment.
Actually: Public IP appear with Private IP value.

**Comment by gabhijit-izel** [comment]
This is something we will revisit later once we figure out about floating IP, whether it should be supported or how this parameter is to be used/shown?

**Comment by pascaljoly** [comment]
feedback I got from customer: they would like to use floating IP as an external IP (not necessarily public) so that the VM management interface can be accessible from test tools outside of the sandbox.

**Comment by alexazarh** [comment]
will be fixed after #17 is done

**Comment by alexazarh** [comment]
will be fixed after #17

**Comment by yairbb** [comment]
@alexazarh 

what did you meant "will be fixed after #17 is done' ?

#17 : this bug was closed from N.A reason. Pls explain.

In any case currently private Ip not appear in filed public Ip .  due to that I will close the bug.
