### ISSUE TITLE
Image UUID should be App attribute for deployment

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#35]
Right now Image Name is used for deployment (eg. cirros). In the cases, where the image names could be duplicate, this could potentially cause a problem while deploying an instance. For this image UUID (from horizon UI) should be taken as an input and not image name.

**Comment by yairbb** [comment]
Hi Abhijit

In case this is response to one of the bugs pls update the waffle.

Regards,

Yair
