### ISSUE TITLE
Power off a terminated machine

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#38]
STR:
1) have a reservation with deployed App ( Powered on Status).
2) Terminate the machine from OpenStack

BIR:
1) Proper Error message shall be obtained.

Actually : Cloudshell behaves like the instance is valid

**Comment by gabhijit-izel** [comment]
Changing the 7.2 label to 7.1 since the error is observed with 7.1

**Comment by gabhijit-izel** [comment]
Done the required changes.

**Comment by yairbb** [comment]
Fix!
