### ISSUE TITLE
Management Network UUID'

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#39]
problem with Management Network UUID. there is no option for deployment

**Comment by gabhijit-izel** [comment]
Can you please elaborate on this?

**Comment by gabhijit-izel** [comment]
I believe - this was the error you faced some time ago. Can you re-test and let me know whether you face this error with new data model?

**Comment by gabhijit-izel** [comment]
Moving it to resolved. Please move to Ready if you face the same problem.

**Comment by yairbb** [comment]
It's Ok now!
