### ISSUE TITLE
Create OpenStack Shell Skeleton

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#4]
Create a Shell skeleton for OpenStack along the lines of AWS-Shell or vCenterShell. Mocked driver that supports the OOB setup, teardown & app orchestration

**Comment by borismod** [comment]
@gabhijit-izel what is your estimation in story points :question:

**Comment by gabhijit-izel** [comment]
I have added it as 5. I am not sure what 5 stands for? Is 5 like 1 person 2-3 days work?

**Comment by borismod** [comment]
Basically it depends on the your team definition. As a starter you can use this: https://github.com/redbooth/Scrum-poker-cards
