### ISSUE TITLE
Remove Cloud Provider related attributes for Floating IP and Security Groups

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#42]
As discussed in the current release, we are not planning to support Floating IP and Security groups as this may not be required. We should be removing the floating IP and security group related attributes from Cloud Provider and Deployment App attributes

**Comment by TomerAdmon** [comment]
remove only SG, we will include the floating IP feature

**Comment by gabhijit-izel** [comment]
Remove the Security Groups related attributes "Inbound Ports" and "OutBound Ports" and add a Default security group Name/ID as an attribute.

**Comment by TomerAdmon** [comment]
related to #17
