### ISSUE TITLE
Refresh IP Command shall not be called during deployment

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#46]
Refresh IP shall not be called during Deployment.

Actually: when setup is running , Refresh IP command is performed.

**Comment by gabhijit-izel** [comment]
Refresh IP is called by setup_environment.py . I am not sure there is any part of CloudShell that is calling it. So that should be fixed?

**Comment by yairbb** [comment]
@alexazarh 
Alex pls check if it comes from setup.

**Comment by alexazarh** [comment]
The setup script is OK. In order to tell the setup script to skip the refresh ip need to add a property to the deploy results called "wait_for_ip". For an example please see how to use it in the aws-shell.

**Comment by yairbb** [comment]
fixed!
