### ISSUE TITLE
Cleanup data model xml

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#49]
Cleanup attribute names and descriptions according to what the product will provide

**Comment by yairbb** [comment]
@TomerAdmon 

pls provide info.

**Comment by TomerAdmon** [comment]
http://confluence.quali.com/pages/viewpage.action?pageId=33652772

**Comment by TomerAdmon** [comment]
[QP-33652772-300117-1206-2.pdf](https://github.com/QualiSystems/OpenStack-Shell/files/738570/QP-33652772-300117-1206-2.pdf)

**Comment by gabhijit-izel** [comment]
@TomerAdmon : Looking at this - Is the attached PDF latest? I have few corrections then 

Reserved Networks: Comma separated list of IP Address CIDRs that are reserved elsewhere. These CIDRs will not be used for App Connectivity (by vNics). 

External Network UUID : To be replaced to Floating IP Pool ID : 

UUID of Subnet or Subnetpool to be used for allocating floating IPs.

---- 

Add floating IP : 
Assign floating IP to instance. ~Use a floating IP to set a static IP using Neutron L3 agent and not using a DHCP service.~ 

Cloud Provider : 
To be removed 

Flavor: (May be we should give the descriptions of "standard flavors"?) 

External Network UUID to be replaced with : Floating IP Pool ID: 

Also please look at #148 and suggest correct icons to use. I believe I have inverted the icons (the image in the PDF is confusing)

**Comment by TomerAdmon** [comment]
Hi @gabhijit-izel 
Here is the latest PDF. 
Reserved Networks: This is the description in other Shells, so it's problematic to change it. @alexazarh - **do you think we should change the name to "OpenStack Reserved Networks" and to give it the correct description?**
External Network - We still need to wrap it up.
Cloud Provider - Removed

[QP-33652772-080217-0935-9.pdf](https://github.com/QualiSystems/OpenStack-Shell/files/759965/QP-33652772-080217-0935-9.pdf)

**Comment by alexazarh** [comment]
I agree

**Comment by TomerAdmon** [comment]
Updated PDF:
[QP-33652772-080217-1020-13.pdf](https://github.com/QualiSystems/OpenStack-Shell/files/760040/QP-33652772-080217-1020-13.pdf)

**Comment by TomerAdmon** [comment]
updated here: 
http://confluence.quali.com/pages/viewpage.action?pageId=33652772

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159496&_a=tests)
