### ISSUE TITLE
Connectivity Q

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#55]
1) what shell be the Connectivity of VMs from separate reservations ?

**Comment by gabhijit-izel** [comment]
We have a pre-created network in Openstack which we call as qualix-network. This is the network on which QualiX VM or Physical machine is to be deployed. Deployment of this should be a pre-condition (as the network UUID of this network is required in Cloud Provider attribute for OpenStack). 

Every VM that gets deployed gets one interface on this network by default. 

The current implementation doesn't support separate Qualix network per reservation and hence this network is shared *across reservations* (This is a security concern, but right now it is not any worse than vCenter). So this is how VMs in reservations 'can potentially connect' to other VMs from different reservations.

**Comment by yairbb** [comment]
@alexazarh  @gabhijit-izel 

Hi abhijit

As far I see in our open stack we have only Quali-network and not qualix. did you meant to that ? ?
