### ISSUE TITLE
Remove affects Q

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#56]
Pls specify which objects shell be removed after Remove or Tear down in the next cases:
1) The last VM was removed.
2) after the remove there still some VM's in the reservation.

Please specify what should be observation in OpenStack

**Comment by gabhijit-izel** [comment]
I am not sure - But you are mostly asking about whether connectivity should be removed? Related to question on #11?

**Comment by yairbb** [comment]
no. I need you to specify which object are affected ( shall be deleted )

**Comment by gabhijit-izel** [comment]
Answer : what happens on OpenStack side.

**Comment by yairbb** [comment]
@alexazarh @TomerAdmon 

Pls refer to the last point .

**Comment by yairbb** [comment]
Removing VM connected P2P will not delete the vlan. In case the second(and the last) VM was removed too the vlan will be deleted too even the reservation still active.
