### ISSUE TITLE
30 VM's Error

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#57]
An Error was obtained In case of deployment 30 Apps using setup in the same reservation. Only 8 Apps were deployed correctly in OpenStack.
This error was obtained by log:"Reservation is Active with Errors - General Execution: Queued command expired due to time-to-live timeout.
"

Actually: All the Apps (30) shell be deployed correctly in OpenStack. The same ability is exist in AWS and Azure.

**Comment by gabhijit-izel** [comment]
Add details of how to update the quota

**Comment by yairbb** [comment]
it's connected to #95 .

closed to prevent duplicate.
