### ISSUE TITLE
Windows VM  in OpenStack

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#58]
Pls create Win7 image besides Cirros for our testing

**Comment by gabhijit-izel** [comment]
Hi Yair,

The documentation on the link below should be straight forward for creating an image for Windows.

http://docs.openstack.org/image-guide/windows-image.html

Let me know if you need any help with this documentation. This mentions for WS2012, but I believe the steps should work for other windows versions (note though that you have to use different Virtio Drivers - should be available on Fedora site).

@TomerAdmon @alexazarh  Can you please take a look at this and let me know if you can find someone to follow these steps and create an image. Or if you download the required image - I can ssh to your machine from here and do these steps. 

Doing these steps locally and then uploading the image will be very tedious.

**Comment by gabhijit-izel** [comment]
Finally managed to boot a windows Instance using an evaluation image from cloudbase. @TomerAdmon  Can you download this image from the following location and keep it on the Openstack machine? I can then create a glance image and try booting it on IL Openstack. Successfully able to deploy on India Openstack

https://cloudbase.it/windows-cloud-images/

**Comment by gabhijit-izel** [comment]
Verified this image works - Built an instance using Cloudshell. Somehow first boot took a very long time (approximately 20mins - The instance was in "Spawning" state). Subsequent instances were created in very short time.

**Comment by yairbb** [comment]
depends #118

**Comment by yairbb** [comment]
Verified!
