### ISSUE TITLE
Deploying VMs on same Compute Node

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#66]
Problem Statement: For one of the applications, it is required that all the VMs are created on Same compute node. 

Explore what is the best possible way to achieve this - 

1. Specify Compute Node in API?
2. Use Availability Zones

Currently selected approach is use of Affinity Groups - 

1. An affinity group is created having policy "affinity" which means all the VMs that are part of this affinity group must be deployed on same compute node (enforced as a policy) 

2. We take as an input an App Attribute (affinity group). If a correct UUID is specified here and policy is 'affinity' then when the VMs are deployed they will be deployed on the same Compute Node. (Note: it is not possible to choose which compute zone we are using - its just guaranteed that whichever is chosen all VMs will be on the same compute node or deployment of a VM could fail).

**Comment by TomerAdmon** [comment]
related to #78

**Comment by alexazarh** [comment]
We want to add this feature by using "Affinity groups".
For this purpose we added a 2nd compute node: 192.168.170.4 to the deployment.

**Comment by gabhijit-izel** [comment]
Also : Right now it's not possible to manage affinity groups through horizon. They should be managed through command line using `nova server-group-create` and `nova server-group-list` etc.

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159632&_a=tests]

**Comment by Shnitselon** [comment]
The only Affinity Group documentation we currently provide is this description for the Affinity Group ID attribute. Anything to add?
======
(Optional) UUID of the affinity group ("nova server-group") to which the instance will be associated. Affinity groups determine on which compute nodes to place instances.
Note: To support the deployment of 'all' OpenStack instances using the same hypervisor, affinity groups with the 'affinity' policy are used.
======

@TomerAdmon @gabhijit-izel @alexazarh
