### ISSUE TITLE
Deploy of snapshot Image.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#69]
Test casa to check validation

**Comment by alexazarh** [comment]
@yairbb Didnt  we test this already?

**Comment by yairbb** [comment]
No. I didnt dealt with that.

**Comment by alexazarh** [comment]
I think you did unknowingly. Every "customized" image is a snapshot.

Best regards,
Alex Azarh

**Comment by yairbb** [comment]
owwwaaa...

so what is the question ? (-:

**Comment by alexazarh** [comment]
The questions is why this issue is not closed?

**Comment by alexazarh** [comment]
I think so
