### ISSUE TITLE
OpenStack Shell deploy cirros image

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#7]
OpenStack Shell implements a model for Cloud Providers family. To be able to test basic working of OpenStack Shell a deployment of an OpenStack VM should be successful. Most Openstack distributions provide a very basic image called 'Cirros'. This is a very light weight image that boots an OS. 

Following use cases should be supported 
1. It should be possible to take image name as an input for deploying instance. The image name should be 'cirros'
2. When wrong image name is provided, the instance will not be successfully created.

In order to support basic deployment - we also should support all of the following instance flavors. An instance flavor is nothing but a specification of Compute + Memory. There are following basic instance flavors defined by OpenStack natively - 
- m1.tiny - 1 VCPU, 512MB
- m1.small - 1VCPU, 2GB
- m1.medium - 2VCPU, 4GB
- m1.large - 4VCPU, 8GB
- m1.xlarge - 8VCPU, 16GB
  Minimum we one flavor should be booting properly, ideally all flavors should be supported.

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=157092)
