### ISSUE TITLE
Hardcoded items in the code

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#72]
Right now during connectivity operation following values are hard-coded in the code

1. Provider network type ('vlan')
2. Provider physical interface ('public')

There might be other instances of hard-coded things in the code. We need to discuss and arrive at a decision where the attributes to be placed or can be placed and where we can take care of this only using Installation Guide.

-abhijit

**Comment by gabhijit-izel** [comment]
@pascaljoly  @yairbb . These are new attributes we have to add to cloud provider. Provider Physical Interface is required by Linux bridge to tell - which physical interface is to be used.

**Comment by TomerAdmon** [comment]
@gabhijit-izel - What about if we are not using Linux Bridge?

**Comment by gabhijit-izel** [comment]
@TomerAdmon : It's required for OVswitch as well, though the exact name for that is not something I don't quickly recollect now. But this value is required.

**Comment by gabhijit-izel** [comment]
To get the value of the "physical network interface". Refer to the following - 
```
/etc/neutron/plugins/ml2/ml2_conf.ini 
[vlan_network_ranges]
```
and 
```
/etc/neutron/plugins/ml2/linuxbridge_agent.ini
physical_network_mappings:
```

**Comment by yairbb** [comment]
@gabhijit-izel 

why did you label this as a "Bug" ?

@TomerAdmon 

Could you Pls add some info and specific req about "Provider physical interface" attribute ?
there is no such issue.

**Comment by yairbb** [comment]
Hi Guys @gabhijit-izel, @TomerAdmon

Pls respond. I want to issued this.

**Comment by gabhijit-izel** [comment]
I think this is a very old bug - you can safely close this. This was before we added those attributes to Cloud Provider

**Comment by yairbb** [comment]
Already implemented.
