### ISSUE TITLE
VXLAN attribute

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#77]
please see issue https://github.com/QualiSystems/Azure-Shell/issues/218

we should add the attribute to the cloudprovider and set it to be VXLAN so the Quali server will use the VXLAN allocaiton range

**Comment by yairbb** [comment]
@TomerAdmon @alexazarh  
Test Plan is needed.

**Comment by TomerAdmon** [comment]
@gabhijit-izel  - Please make sure that this attribute is a lookup that have "Vlan / Vxlan"

**Comment by yairbb** [comment]
shall be checked on CS 8.0

**Comment by yairbb** [comment]
@TomerAdmon 

VLAN shall be till 4094.

**Comment by TomerAdmon** [comment]
@yairbb - is that a question?

**Comment by yairbb** [comment]
@TomerAdmon 
no. conclusion  :-)

Am I wrong ?

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=158841&_a=tests)
