### ISSUE TITLE
test with open vswitch

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#83]

**Comment by TomerAdmon** [comment]
Usually when we test using the India or IL OpenStack installation we are using Linux brigde as the  connectivity provider. This is not commonly used with production OpenStack installations but with smaller ones or testing ones. Usually, it will be preferred to use Open VSwitch. This task will require to update one of the OpenStack installations to use the OVSwitch and to test main flows with it, with vlan and vxlan.
http://docs.openstack.org/mitaka/networking-guide/scenario-classic-ovs.html

**Comment by gabhijit-izel** [comment]
OpenVswitch is deployed on Israel OpenStack and instances deployed are getting network connectivity. Will close this issue after a couple of days of testing.

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159677&_a=tests)

**Comment by alexazarh** [comment]
blocked by #193
