### ISSUE TITLE
CP & deployment type Icons

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#84]

**Comment by TomerAdmon** [comment]
Deployment option icon
[OpenStack_VM.zip](https://github.com/QualiSystems/OpenStack-Shell/files/661380/OpenStack_VM.zip)

**Comment by TomerAdmon** [comment]
Here are the icons

[CloudProvider.zip](https://github.com/QualiSystems/OpenStack-Shell/files/661623/CloudProvider.zip)
[DeploymentType.zip](https://github.com/QualiSystems/OpenStack-Shell/files/661624/DeploymentType.zip)

**Comment by gabhijit-izel** [comment]
Can you please Check CloudProvider.zip ?? I Believe it still has OpenStack VM Icon and Not OpenStack Cloud Provider Icon? Because both of them look identical. (One in DeploymentType and Cloudprovider)

**Comment by TomerAdmon** [comment]
@gabhijit-izel  - The name of the files inside the zip is wrong... but this is the logo we would like to use....

**Comment by yairbb** [comment]
@gabhijit-izel 
there is a mismatch the same icons were configured.
