### ISSUE TITLE
Error during deployment

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#86]
This issue was observed on latest develop branch when tried to deploy a blueprint with two VMs and 3 VLAN Service Apps.

Setup has thrown an "Index Error". 

Rerunning the setup was successful. So need to find out more what caused the error

**Comment by TomerAdmon** [comment]
Unstable

**Comment by gabhijit-izel** [comment]
Closing this issue since no more data is available. Will create new one if found during testing.
