### ISSUE TITLE
Test VXlan connectivity for real (with 7.2)

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#87]
when testing with 7.1, the VXlan is not really in used in the server side. In 7.2 we already have the server side pool Vxlan range implemented.
need to test that the the VXlan is working with the new range of vlan ids

**Comment by yairbb** [comment]
{Test Plan}[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=158841&_a=tests]
