### ISSUE TITLE
Connectivity - Vlan Trunk/Access

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#89]

**Comment by TomerAdmon** [comment]
waiting for #83

**Comment by gabhijit-izel** [comment]
My current understanding for this feature is as follows - 

If Trunk support is requested in Connectivity - it should be possible to create an interface on the VM that supports VLANs in Trunk ranges - something described below. 

There are two pieces to this actually - after doing a lot more study - 
1. Neutron support for VLAN Transparent networks 
2. Neutron Trunk support 

While Support for 1. has been around for a while (Not all L2 drivers support it. The documentation is at-best misleading. :-) But trunk port support seems to be a very recent one. So we are not going to support Trunk port out of the box. If this feature is required - we have to figure out a configuration that works and then say - that with this particular configuration this can be supported (but a generic support is not available).

for example - 
http://www.jimmdenton.com/neutron-trunks/

**Comment by Shnitselon** [comment]
added a note to the vlan connectivity and openstack known issues topics saying Trunk is not supported for OpenStack
@TomerAdmon  @gabhijit-izel
